<?php

function bdCrea(PDO $con)
{
  // Tabla de usuarios (candidatos)
  $con->exec('
    CREATE TABLE IF NOT EXISTS USUARIO (
      US_ID INTEGER PRIMARY KEY AUTOINCREMENT,
      US_NOMBRE TEXT NOT NULL,
      US_APELLIDO TEXT NOT NULL,
      US_CORREO TEXT NOT NULL UNIQUE,
      US_CONTRASENA TEXT NOT NULL,
      US_CV BLOB,
      US_FECHA_REGISTRO DATE DEFAULT CURRENT_DATE
    );
  ');

  // Tabla de reclutadores
  $con->exec('
    CREATE TABLE IF NOT EXISTS RECLUTADOR (
      REC_ID INTEGER PRIMARY KEY AUTOINCREMENT,
      REC_NOMBRE TEXT NOT NULL,
      REC_CORREO TEXT NOT NULL UNIQUE,
      REC_CONTRASENA TEXT NOT NULL
    );
  ');

  // Tabla de preguntas psicométricas
  $con->exec('
    CREATE TABLE IF NOT EXISTS PSICOPREGUNTA (
      PSI_ID INTEGER PRIMARY KEY AUTOINCREMENT,
      PSI_TEXTO TEXT NOT NULL
    );
  ');

  // Tabla de respuestas psicométricas
  $con->exec('
    CREATE TABLE IF NOT EXISTS PSICORESPUESTA (
      RES_ID INTEGER PRIMARY KEY AUTOINCREMENT,
      RES_USUARIO_ID INTEGER NOT NULL,
      RES_PREGUNTA_ID INTEGER NOT NULL,
      RES_OPCION TEXT NOT NULL,
      FOREIGN KEY (RES_USUARIO_ID) REFERENCES USUARIO(US_ID),
      FOREIGN KEY (RES_PREGUNTA_ID) REFERENCES PSICOPREGUNTA(PSI_ID)
    );
  ');

  // Tabla de preguntas técnicas (conocimiento TI)
  $con->exec('
    CREATE TABLE IF NOT EXISTS TECHPREGUNTA (
      TECH_ID INTEGER PRIMARY KEY AUTOINCREMENT,
      TECH_TEXTO TEXT NOT NULL,
      TECH_OPCION_A TEXT NOT NULL,
      TECH_OPCION_B TEXT NOT NULL,
      TECH_OPCION_C TEXT NOT NULL,
      TECH_OPCION_D TEXT NOT NULL,
      TECH_CORRECTA TEXT NOT NULL
    );
  ');

  // Tabla de respuestas técnicas
  $con->exec('
    CREATE TABLE IF NOT EXISTS TECHRESPUESTA (
      TRESP_ID INTEGER PRIMARY KEY AUTOINCREMENT,
      TRESP_USUARIO_ID INTEGER NOT NULL,
      TRESP_PREGUNTA_ID INTEGER NOT NULL,
      TRESP_RESPUESTA TEXT NOT NULL,
      FOREIGN KEY (TRESP_USUARIO_ID) REFERENCES USUARIO(US_ID),
      FOREIGN KEY (TRESP_PREGUNTA_ID) REFERENCES TECHPREGUNTA(TECH_ID)
    );
  ');

  // Tabla de resultados finales
  $con->exec('
    CREATE TABLE IF NOT EXISTS RESULTADO (
      RES_ID INTEGER PRIMARY KEY AUTOINCREMENT,
      RES_USUARIO_ID INTEGER NOT NULL,
      RES_FECHA DATE DEFAULT CURRENT_DATE,
      RES_PSI_SCORE INTEGER,
      RES_TECH_SCORE INTEGER,
      RES_VEREDICTO TEXT,
      FOREIGN KEY (RES_USUARIO_ID) REFERENCES USUARIO(US_ID)
    );
  ');
}
